FROM postgres:16-alpine

RUN apk add --no-cache \
    build-base \
    postgresql-dev \
    git

RUN git clone https://github.com/pgvector/pgvector.git /tmp/pgvector && \
    cd /tmp/pgvector && \
    make && \
    make install && \
    rm -rf /tmp/pgvector
